<?php

    if (empty($vid)){
        $channellist = array("
            肥米TV节目源动态代理,KwanKaHo@luo2888.cn
            QQ:625336209
            
            VID列表：
                CIBN：cibn
                荔枝网：grtn
                天途云：tty
                咪咕视频：migu
                香港无线：tvb
                香港有线：utvhk
                龙腾TV：lttv
                SmartTV(支持2线切换)：暂时下架
                牛牛直播(支持多线切换)：nnzb
                IPTV345(支持多线切换)：iptv345
                IPTV2020(支持多线切换)：iptv2020
        ");
    }
    
    if ($vid == 'iptv345' || $vid == 'iptv2020') {
        if (empty($tid)) {
            $channellist = array('
                肥米TV节目源动态代理,KwanKaHo@luo2888.cn
                
                TID列表：
                    综合：itv
                    体育：ty
                    央视：ys
                    卫视：ws
                    北邮：bupt
                    港澳台：gt
                    港澳台新源：wintv123
                    其他（国外）：other
                    电影轮播：movie
                    咪咕视频：migu
                    北方云：bfiptv
                    广西联通：ltiptv
                    福建移动：fjitv
                    湖北广电：hrtn
                    黑龙江移动：hlitv
                    天途云：tt
                    珠江宽频：zjkp');
            if ($vid == 'iptv345') { $channellist = preg_replace('#wintv123#', '不支持', $channellist); }
        } else {
            $url = "https://player.ggiptv.com/iptv.php?tid=$tid";
            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, $url);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
            curl_setopt($curl, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/x-www-form-urlencoded'
            ));
            curl_setopt($curl, CURLOPT_USERAGENT, 'MQQBrowser/6.2 TBS/045130 MicroMessengeriptv VideoPlayer god/3.0.0 Html5Plus/1.0 (Immersed/29.411766)');
            $curlobj = curl_exec($curl);
            preg_match_all('/token=(.*?)&tid=(.*?)&id=(.*?)" data-ajax="false">(.*?)</i', $curlobj, $channel);
            $i = 0;
            foreach ($channel[4] as &$channelname) {
                $channelname = preg_replace('#凤凰卫视#', '凤凰', $channelname);
                $channelname = preg_replace('#\(HD\)#', '', $channelname);
                $channelname = preg_replace('# #', '', $channelname);
                $channellist[] = $channelname . ",http://你的域名/文件名?act=play&vid=$vid&tid=$tid&id=" . $channel[3][$i];
                $i++;
            }
        }
    }
    
    if ($vid == 'cibn') {
        $channellist = array('
            CIBN精品影院,http://你的域名/文件名?act=play&vid=cibn&id=0
            CIBN生活,http://你的域名/文件名?act=play&vid=cibn&id=1
            CIBN军事,http://你的域名/文件名?act=play&vid=cibn&id=2
            CIBN真人秀,http://你的域名/文件名?act=play&vid=cibn&id=3
            CIBN怡家,http://你的域名/文件名?act=play&vid=cibn&id=4
            CIBN文旅中国,http://你的域名/文件名?act=play&vid=cibn&id=5
            CIBN今日推荐,http://你的域名/文件名?act=play&vid=cibn&id=6
            CIBN嗨播,http://你的域名/文件名?act=play&vid=cibn&id=7
            CIBN时尚生活,http://你的域名/文件名?act=play&vid=cibn&id=8
            CIBN童学世界,http://你的域名/文件名?act=play&vid=cibn&id=9
            CIBN经典剧场,http://你的域名/文件名?act=play&vid=cibn&id=10
            CIBN风尚运动,http://你的域名/文件名?act=play&vid=cibn&id=11
            CIBN汽车,http://你的域名/文件名?act=play&vid=cibn&id=12
            CIBN快乐购物,http://你的域名/文件名?act=play&vid=cibn&id=13
            CIBN映画,http://你的域名/文件名?act=play&vid=cibn&id=14
            CIBN MV,http://你的域名/文件名?act=play&vid=cibn&id=15
            CIBN情感影院,http://你的域名/文件名?act=play&vid=cibn&id=16
            CIBN骄阳剧场,http://你的域名/文件名?act=play&vid=cibn&id=17
            CIBN健康,http://你的域名/文件名?act=play&vid=cibn&id=18
            CIBN流行榜单,http://你的域名/文件名?act=play&vid=cibn&id=19
            CIBN底价秒杀,http://你的域名/文件名?act=play&vid=cibn&id=20
            CIBN全电竞,http://你的域名/文件名?act=play&vid=cibn&id=21
            CIBN喜剧影院,http://你的域名/文件名?act=play&vid=cibn&id=22
            CIBN炫佳动漫,http://你的域名/文件名?act=play&vid=cibn&id=23
            CIBN微电影,http://你的域名/文件名?act=play&vid=cibn&id=24
            CIBN巨星演唱会,http://你的域名/文件名?act=play&vid=cibn&id=25
            CIBN家装精选,http://你的域名/文件名?act=play&vid=cibn&id=26
            CIBN美食厨房,http://你的域名/文件名?act=play&vid=cibn&id=27
            CIBN热卖推荐,http://你的域名/文件名?act=play&vid=cibn&id=28
            CIBN院线大片,http://你的域名/文件名?act=play&vid=cibn&id=29
            CIBN品质生活,http://你的域名/文件名?act=play&vid=cibn&id=30
            CIBN古装剧场,http://你的域名/文件名?act=play&vid=cibn&id=31
            CIBN经典音乐,http://你的域名/文件名?act=play&vid=cibn&id=32
            CIBN动漫剧场,http://你的域名/文件名?act=play&vid=cibn&id=33
            CIBN好莱坞,http://你的域名/文件名?act=play&vid=cibn&id=34
            CIBN家居用品,http://你的域名/文件名?act=play&vid=cibn&id=35
            CIBN朵丫乐园,http://你的域名/文件名?act=play&vid=cibn&id=36
            CIBN女团专场,http://你的域名/文件名?act=play&vid=cibn&id=37
            CIBN斗牛财经,http://你的域名/文件名?act=play&vid=cibn&id=38
            CIBN流金岁月,http://你的域名/文件名?act=play&vid=cibn&id=39
            CIBN老陈坐弹会,http://你的域名/文件名?act=play&vid=cibn&id=40
            CIBN好物,http://你的域名/文件名?act=play&vid=cibn&id=41
            CIBN艺术院线,http://你的域名/文件名?act=play&vid=cibn&id=42
            CIBN音乐综艺,http://你的域名/文件名?act=play&vid=cibn&id=43
            CIBN精选古典乐,http://你的域名/文件名?act=play&vid=cibn&id=44
            CIBN经典音乐会,http://你的域名/文件名?act=play&vid=cibn&id=45
            CIBN新知,http://你的域名/文件名?act=play&vid=cibn&id=46
            CIBN电影综合,http://你的域名/文件名?act=play&vid=cibn&id=47
            CIBN中国交通,http://你的域名/文件名?act=play&vid=cibn&id=48
            CIBN纪录片,http://你的域名/文件名?act=play&vid=cibn&id=49
            CIBN环球奇观,http://你的域名/文件名?act=play&vid=cibn&id=50
            CIBN收藏,http://你的域名/文件名?act=play&vid=cibn&id=51
            CIBN莎翁戏剧,http://你的域名/文件名?act=play&vid=cibn&id=52
            CIBN综合,http://你的域名/文件名?act=play&vid=cibn&id=53
            CIBN动作影院,http://你的域名/文件名?act=play&vid=cibn&id=54
        ');
    }
    
    if ($vid == 'grtn') {
        $channellist = array('
            广东南方,http://你的域名/文件名?act=play&vid=grtn&id=7
            广东珠江,http://你的域名/文件名?act=play&vid=grtn&id=26
            广东卫视,http://你的域名/文件名?act=play&vid=grtn&id=25
            广东体育,http://你的域名/文件名?act=play&vid=grtn&id=27
            嘉佳卡通,http://你的域名/文件名?act=play&vid=grtn&id=29
            广东新闻,http://你的域名/文件名?act=play&vid=grtn&id=28
            广东公共,http://你的域名/文件名?act=play&vid=grtn&id=31
            广东国际,http://你的域名/文件名?act=play&vid=grtn&id=30
            广东影视,http://你的域名/文件名?act=play&vid=grtn&id=37
            广东房产,http://你的域名/文件名?act=play&vid=grtn&id=33
            广东少儿,http://你的域名/文件名?act=play&vid=grtn&id=38
            广东移动,http://你的域名/文件名?act=play&vid=grtn&id=101
            广东综艺,http://你的域名/文件名?act=play&vid=grtn&id=166
            广东珠江,http://你的域名/文件名?act=play&vid=grtn&id=172
            广东高尔夫,http://你的域名/文件名?act=play&vid=grtn&id=32
            广东经济科教,http://你的域名/文件名?act=play&vid=grtn&id=93
            广东南方购物,http://你的域名/文件名?act=play&vid=grtn&id=95
            广东岭南戏曲,http://你的域名/文件名?act=play&vid=grtn&id=167
            广东现代教育,http://你的域名/文件名?act=play&vid=grtn&id=169
            汕头综合,http://你的域名/文件名?act=play&vid=grtn&id=61
            佛山综合,http://你的域名/文件名?act=play&vid=grtn&id=62
            茂名综合,http://你的域名/文件名?act=play&vid=grtn&id=63
            肇庆综合,http://你的域名/文件名?act=play&vid=grtn&id=65
            韶关综合,http://你的域名/文件名?act=play&vid=grtn&id=64
            河源综合,http://你的域名/文件名?act=play&vid=grtn&id=67
            潮州综合,http://你的域名/文件名?act=play&vid=grtn&id=68
            惠州综合,http://你的域名/文件名?act=play&vid=grtn&id=78
            江门综合,http://你的域名/文件名?act=play&vid=grtn&id=79
            揭阳综合,http://你的域名/文件名?act=play&vid=grtn&id=83
            清远综合,http://你的域名/文件名?act=play&vid=grtn&id=82
            云浮综合,http://你的域名/文件名?act=play&vid=grtn&id=85
            东莞-1,http://你的域名/文件名?act=play&vid=grtn&id=76
            珠海-1,http://你的域名/文件名?act=play&vid=grtn&id=75
            汕尾-1,http://你的域名/文件名?act=play&vid=grtn&id=81
            阳江-1,http://你的域名/文件名?act=play&vid=grtn&id=84
        ');
    }
    
    if ($vid == 'tvb') {
        $channellist = array('
            无线新闻,http://你的域名/文件名?act=play&vid=tvb&id=inews
            无线财经资讯,http://你的域名/文件名?act=play&vid=tvb&id=j5_ch85
        ');
    }
    
    if ($vid == 'utvhk') {
        $channellist = array('
            有线新闻,http://你的域名/文件名?act=play&vid=utvhk&id=657254667
            有线综合娱乐,http://你的域名/文件名?act=play&vid=utvhk&id=662547571
            有线财经资讯,http://你的域名/文件名?act=play&vid=utvhk&id=657254837
        ');
    }
    
    if ($vid == 'pygd') {
        $channellist = array('
            晋中一台,http://你的域名/文件名?act=play&vid=pygd&id=006
            晋中二台,http://你的域名/文件名?act=play&vid=pygd&id=178
        ');
    }
    
    if ($vid == 'lttv') {
        $channellist = array('
            TVB翡翠,http://你的域名/文件名?act=play&vid=lttv&id=ch101
            J2,http://你的域名/文件名?act=play&vid=lttv&id=ch102
            无线财经,http://你的域名/文件名?act=play&vid=lttv&id=ch103
            TVB明珠,http://你的域名/文件名?act=play&vid=lttv&id=ch104
            无线新闻,http://你的域名/文件名?act=play&vid=lttv&id=ch201
            TVB星河,http://你的域名/文件名?act=play&vid=lttv&id=ch105
            星河国语,http://你的域名/文件名?act=play&vid=lttv&id=ch108
            有线新闻,http://你的域名/文件名?act=play&vid=lttv&id=ch109
            凤凰电影,http://你的域名/文件名?act=play&vid=lttv&id=ch110
            thrill,http://你的域名/文件名?act=play&vid=lttv&id=ch112
            TVB经典,http://你的域名/文件名?act=play&vid=lttv&id=ch113
            卫视国际电影,http://你的域名/文件名?act=play&vid=lttv&id=ch111
            NOW新闻,http://你的域名/文件名?act=play&vid=lttv&id=ch114
            ViuTV,http://你的域名/文件名?act=play&vid=lttv&id=ch115
            ViuTV6,http://你的域名/文件名?act=play&vid=lttv&id=ch116
            有线财经,http://你的域名/文件名?act=play&vid=lttv&id=ch117
            有线娱乐,http://你的域名/文件名?act=play&vid=lttv&id=ch118
            有线18台,http://你的域名/文件名?act=play&vid=lttv&id=ch119
            龙翔电影,http://你的域名/文件名?act=play&vid=lttv&id=ch301
            纬来电影,http://你的域名/文件名?act=play&vid=lttv&id=ch302
            东森洋片,http://你的域名/文件名?act=play&vid=lttv&id=ch303
            卫视电影,http://你的域名/文件名?act=play&vid=lttv&id=ch304
            星卫电影,http://你的域名/文件名?act=play&vid=lttv&id=ch305
            美亚电影,http://你的域名/文件名?act=play&vid=lttv&id=ch306
            卫视洋片,http://你的域名/文件名?act=play&vid=lttv&id=ch307
            东森电影,http://你的域名/文件名?act=play&vid=lttv&id=ch308
            龙华洋片,http://你的域名/文件名?act=play&vid=lttv&id=ch309
            HBOHD,http://你的域名/文件名?act=play&vid=lttv&id=ch310
            HBOHITS,http://你的域名/文件名?act=play&vid=lttv&id=ch311
            HBOignature,http://你的域名/文件名?act=play&vid=lttv&id=ch312
            HBOfamlly,http://你的域名/文件名?act=play&vid=lttv&id=ch313
            中视,http://你的域名/文件名?act=play&vid=lttv&id=ch202
            华视,http://你的域名/文件名?act=play&vid=lttv&id=ch203
            民视,http://你的域名/文件名?act=play&vid=lttv&id=ch204
            台视,http://你的域名/文件名?act=play&vid=lttv&id=ch205
            CNN,http://你的域名/文件名?act=play&vid=lttv&id=ch315
            寰宇新聞,http://你的域名/文件名?act=play&vid=lttv&id=ch211
            TVBS新聞,http://你的域名/文件名?act=play&vid=lttv&id=ch215
            东森新闻,http://你的域名/文件名?act=play&vid=lttv&id=ch217
            中天新闻,http://你的域名/文件名?act=play&vid=lttv&id=zhongtianxw
            国家地理,http://你的域名/文件名?act=play&vid=lttv&id=ch316
            中天新闻,http://你的域名/文件名?act=play&vid=lttv2&id=tw101
            台視新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw102
            華視新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw103
            TVBS新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw104
            民視新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw105
            东森新闻,http://你的域名/文件名?act=play&vid=lttv2&id=tw106
            中視新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw107
            TVBS,http://你的域名/文件名?act=play&vid=lttv2&id=tw108
            三立財經,http://你的域名/文件名?act=play&vid=lttv2&id=tw109
            非凡新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw110
            东森财经,http://你的域名/文件名?act=play&vid=lttv2&id=tw111
            东森亚洲新闻,http://你的域名/文件名?act=play&vid=lttv2&id=tw112
            寰宇新聞2,http://你的域名/文件名?act=play&vid=lttv2&id=tw113
            寰宇新聞,http://你的域名/文件名?act=play&vid=lttv2&id=tw114
            壹新闻,http://你的域名/文件名?act=play&vid=lttv2&id=tw115
            年代新闻,http://你的域名/文件名?act=play&vid=lttv2&id=tw116
            三立新闻,http://你的域名/文件名?act=play&vid=lttv2&id=tw117
            卫视电影台,http://你的域名/文件名?act=play&vid=lttv3&id=ws101
            RHK31,http://你的域名/文件名?act=play&vid=lttv3&id=ws102
            FOXHD,http://你的域名/文件名?act=play&vid=lttv3&id=ws104
            FoxActionMovies,http://你的域名/文件名?act=play&vid=lttv3&id=ws105
            FoxFamily,http://你的域名/文件名?act=play&vid=lttv3&id=ws106
            FoxCrime,http://你的域名/文件名?act=play&vid=lttv3&id=ws107
            FXHD,http://你的域名/文件名?act=play&vid=lttv3&id=ws108
            天映频道,http://你的域名/文件名?act=play&vid=lttv3&id=ws109
            天映经典,http://你的域名/文件名?act=play&vid=lttv3&id=ws110
            八大综合,http://你的域名/文件名?act=play&vid=lttv3&id=ws121
            八大第一,http://你的域名/文件名?act=play&vid=lttv3&id=ws122
            八大戏剧,http://你的域名/文件名?act=play&vid=lttv3&id=ws123
            三立综合,http://你的域名/文件名?act=play&vid=lttv3&id=ws124
            三立都会,http://你的域名/文件名?act=play&vid=lttv3&id=ws125
            三立戏剧,http://你的域名/文件名?act=play&vid=lttv3&id=ws126
            三立台湾,http://你的域名/文件名?act=play&vid=lttv3&id=ws127
            东森戏剧,http://你的域名/文件名?act=play&vid=lttv3&id=ws128
            东森综合,http://你的域名/文件名?act=play&vid=lttv3&id=ws131
            纬来戏剧,http://你的域名/文件名?act=play&vid=lttv3&id=ws132
            纬来综合,http://你的域名/文件名?act=play&vid=lttv3&id=ws133
            纬来育乐,http://你的域名/文件名?act=play&vid=lttv3&id=ws135
            纬来日本,http://你的域名/文件名?act=play&vid=lttv3&id=ws136
            緯來體育,http://你的域名/文件名?act=play&vid=lttv3&id=ws138
            EYETV戏剧,http://你的域名/文件名?act=play&vid=lttv3&id=ws139
            爱尔达影剧,http://你的域名/文件名?act=play&vid=lttv3&id=ws140
            美食星球,http://你的域名/文件名?act=play&vid=lttv3&id=ws141
            国家地理悠人,http://你的域名/文件名?act=play&vid=lttv3&id=ws143
            国家地理野生,http://你的域名/文件名?act=play&vid=lttv3&id=ws145
            动物星球,http://你的域名/文件名?act=play&vid=lttv3&id=ws151
        ');
    }
    
    if ($vid == 'tty') {
        $channellist = array('
            CCTV-1,http://你的域名/文件名?act=play&vid=tty&id=133
            CCTV-2,http://你的域名/文件名?act=play&vid=tty&id=217
            CCTV-3,http://你的域名/文件名?act=play&vid=tty&id=134
            CCTV-4,http://你的域名/文件名?act=play&vid=tty&id=315
            CCTV-5,http://你的域名/文件名?act=play&vid=tty&id=135
            CCTV-5Plus,http://你的域名/文件名?act=play&vid=tty&id=138
            CCTV-6,http://你的域名/文件名?act=play&vid=tty&id=136
            CCTV-7,http://你的域名/文件名?act=play&vid=tty&id=241
            CCTV-8,http://你的域名/文件名?act=play&vid=tty&id=137
            CCTV-9,http://你的域名/文件名?act=play&vid=tty&id=249
            CCTV-10,http://你的域名/文件名?act=play&vid=tty&id=218
            CCTV-11,http://你的域名/文件名?act=play&vid=tty&id=324
            CCTV-12,http://你的域名/文件名?act=play&vid=tty&id=219
            CCTV-13,http://你的域名/文件名?act=play&vid=tty&id=022
            CCTV-14,http://你的域名/文件名?act=play&vid=tty&id=248
            CCTV-15,http://你的域名/文件名?act=play&vid=tty&id=325
            CCTV-15,http://你的域名/文件名?act=play&vid=tty&id=024
            CCTV-17,http://你的域名/文件名?act=play&vid=tty&id=241
            CETV-1,http://你的域名/文件名?act=play&vid=tty&id=256
            CGTN纪录,http://你的域名/文件名?act=play&vid=tty&id=234
            CGTN,http://你的域名/文件名?act=play&vid=tty&id=260
            CGTN法语,http://你的域名/文件名?act=play&vid=tty&id=230
            CGTN阿语,http://你的域名/文件名?act=play&vid=tty&id=231
            CGTN葡语,http://你的域名/文件名?act=play&vid=tty&id=233
            CGTN西语,http://你的域名/文件名?act=play&vid=tty&id=233
            辽宁卫视,http://你的域名/文件名?act=play&vid=tty&id=139
            湖南卫视,http://你的域名/文件名?act=play&vid=tty&id=140
            东方卫视,http://你的域名/文件名?act=play&vid=tty&id=141
            江苏卫视,http://你的域名/文件名?act=play&vid=tty&id=142
            浙江卫视,http://你的域名/文件名?act=play&vid=tty&id=143
            黑龙江卫视,http://你的域名/文件名?act=play&vid=tty&id=144
            广东卫视,http://你的域名/文件名?act=play&vid=tty&id=145
            深圳卫视,http://你的域名/文件名?act=play&vid=tty&id=146
            北京卫视,http://你的域名/文件名?act=play&vid=tty&id=147
            安徽卫视,http://你的域名/文件名?act=play&vid=tty&id=148
            天津卫视,http://你的域名/文件名?act=play&vid=tty&id=149
            山东卫视,http://你的域名/文件名?act=play&vid=tty&id=221
            重庆卫视,http://你的域名/文件名?act=play&vid=tty&id=222
            湖北卫视,http://你的域名/文件名?act=play&vid=tty&id=250
            贵州卫视,http://你的域名/文件名?act=play&vid=tty&id=251
            东南卫视,http://你的域名/文件名?act=play&vid=tty&id=252
            河北卫视,http://你的域名/文件名?act=play&vid=tty&id=253
            四川卫视,http://你的域名/文件名?act=play&vid=tty&id=254
            江西卫视,http://你的域名/文件名?act=play&vid=tty&id=255
            河南卫视,http://你的域名/文件名?act=play&vid=tty&id=312
            吉林卫视,http://你的域名/文件名?act=play&vid=tty&id=313
            广西卫视,http://你的域名/文件名?act=play&vid=tty&id=034
            陕西卫视,http://你的域名/文件名?act=play&vid=tty&id=036
            内蒙古卫视,http://你的域名/文件名?act=play&vid=tty&id=040
            云南卫视,http://你的域名/文件名?act=play&vid=tty&id=052
            山西卫视,http://你的域名/文件名?act=play&vid=tty&id=054
            江西卫视,http://你的域名/文件名?act=play&vid=tty&id=055
            宁夏卫视,http://你的域名/文件名?act=play&vid=tty&id=056
            甘肃卫视,http://你的域名/文件名?act=play&vid=tty&id=058
            西藏卫视,http://你的域名/文件名?act=play&vid=tty&id=063
            兵团卫视,http://你的域名/文件名?act=play&vid=tty&id=189
            新疆卫视,http://你的域名/文件名?act=play&vid=tty&id=259
            辽宁都市,http://你的域名/文件名?act=play&vid=tty&id=026
            辽宁影视剧,http://你的域名/文件名?act=play&vid=tty&id=027
            辽宁体育,http://你的域名/文件名?act=play&vid=tty&id=028
            辽宁北方,http://你的域名/文件名?act=play&vid=tty&id=030
            辽宁公共,http://你的域名/文件名?act=play&vid=tty&id=064
            辽宁经济,http://你的域名/文件名?act=play&vid=tty&id=188
            辽宁生活,http://你的域名/文件名?act=play&vid=tty&id=190
            辽宁教育青少,http://你的域名/文件名?act=play&vid=tty&id=191
            辽宁家政,http://你的域名/文件名?act=play&vid=tty&id=215
            大连1,http://你的域名/文件名?act=play&vid=tty&id=132
            大连2,http://你的域名/文件名?act=play&vid=tty&id=002
            大连3,http://你的域名/文件名?act=play&vid=tty&id=003
            大连4,http://你的域名/文件名?act=play&vid=tty&id=004
            大连5,http://你的域名/文件名?act=play&vid=tty&id=005
            大连6,http://你的域名/文件名?act=play&vid=tty&id=006
            大连7,http://你的域名/文件名?act=play&vid=tty&id=007
            大连8,http://你的域名/文件名?act=play&vid=tty&id=235
            大连导视,http://你的域名/文件名?act=play&vid=tty&id=009
            北京纪实,http://你的域名/文件名?act=play&vid=tty&id=314
            未知1,http://你的域名/文件名?act=play&vid=tty&id=131
            东方财经,http://你的域名/文件名?act=play&vid=tty&id=066
            梨园频道,http://你的域名/文件名?act=play&vid=tty&id=067
            留学世界,http://你的域名/文件名?act=play&vid=tty&id=068
            女性时尚,http://你的域名/文件名?act=play&vid=tty&id=069
            央视文化精品,http://你的域名/文件名?act=play&vid=tty&id=071
            汽摩,http://你的域名/文件名?act=play&vid=tty&id=072
            靓妆,http://你的域名/文件名?act=play&vid=tty&id=073
            现代女性,http://你的域名/文件名?act=play&vid=tty&id=074
            中国气象频道,http://你的域名/文件名?act=play&vid=tty&id=076
            教育就业,http://你的域名/文件名?act=play&vid=tty&id=077
            休闲,http://你的域名/文件名?act=play&vid=tty&id=078
            茶频道,http://你的域名/文件名?act=play&vid=tty&id=079
            中学生,http://你的域名/文件名?act=play&vid=tty&id=082
            法制天地,http://你的域名/文件名?act=play&vid=tty&id=192
            央视台球,http://你的域名/文件名?act=play&vid=tty&id=198
            快乐垂钓,http://你的域名/文件名?act=play&vid=tty&id=199
            彩民在线,http://你的域名/文件名?act=play&vid=tty&id=200
            武术世界,http://你的域名/文件名?act=play&vid=tty&id=202
            新科动漫,http://你的域名/文件名?act=play&vid=tty&id=203
            文物宝库,http://你的域名/文件名?act=play&vid=tty&id=204
            天元围棋,http://你的域名/文件名?act=play&vid=tty&id=205
            深圳DV生活,http://你的域名/文件名?act=play&vid=tty&id=206
            央视电视指南,http://你的域名/文件名?act=play&vid=tty&id=207
            七彩戏剧,http://你的域名/文件名?act=play&vid=tty&id=209
            老年福,http://你的域名/文件名?act=play&vid=tty&id=210
            金色频道,http://你的域名/文件名?act=play&vid=tty&id=212
            美食天府,http://你的域名/文件名?act=play&vid=tty&id=213
            老故事,http://你的域名/文件名?act=play&vid=tty&id=262
            人物频道,http://你的域名/文件名?act=play&vid=tty&id=264
            北京纪实,http://你的域名/文件名?act=play&vid=tty&id=311
            卫生健康,http://你的域名/文件名?act=play&vid=tty&id=316
            金鹰卡通,http://你的域名/文件名?act=play&vid=tty&id=257
            卡酷少儿,http://你的域名/文件名?act=play&vid=tty&id=258
        ');
    }
    
    if ($vid == 'migu') {
        $channellist = array('
            CCTV-1综合,http://你的域名/文件名?act=play&vid=migu&id=608807420
            CCTV-1综合,http://你的域名/文件名?act=play&vid=migu&id=608807427
            CCTV-2财经,http://你的域名/文件名?act=play&vid=migu&id=631780532
            CCTV-3综艺,http://你的域名/文件名?act=play&vid=migu&id=624878268
            CCTV-4中文国际,http://你的域名/文件名?act=play&vid=migu&id=631780421
            CCTV-4中文国际,http://你的域名/文件名?act=play&vid=migu&id=608807424
            CCTV-5体育,http://你的域名/文件名?act=play&vid=migu&id=641886657
            CCTV5Plus体育赛事,http://你的域名/文件名?act=play&vid=migu&id=641886733
            CCTV-6电影,http://你的域名/文件名?act=play&vid=migu&id=608919883
            CCTV-7军事农业,http://你的域名/文件名?act=play&vid=migu&id=609018153
            CCTV-8电视剧,http://你的域名/文件名?act=play&vid=migu&id=609154254
            CCTV-9纪录,http://你的域名/文件名?act=play&vid=migu&id=608920109
            CCTV-9Documentary,http://你的域名/文件名?act=play&vid=migu&id=609006487
            CCTV-10科教,http://你的域名/文件名?act=play&vid=migu&id=608880731
            CCTV-11戏曲,http://你的域名/文件名?act=play&vid=migu&id=609017121
            CCTV-12社会与法,http://你的域名/文件名?act=play&vid=migu&id=609017191
            CCTV-13新闻,http://你的域名/文件名?act=play&vid=migu&id=608807423
            CCTV-14少儿,http://你的域名/文件名?act=play&vid=migu&id=609017204
            CCTV-14少儿,http://你的域名/文件名?act=play&vid=migu&id=624878440
            CCTV-15音乐,http://你的域名/文件名?act=play&vid=migu&id=608807408
            CCTV-17农业农村,http://你的域名/文件名?act=play&vid=migu&id=660321844
            CCTV法语,http://你的域名/文件名?act=play&vid=migu&id=609006476
            CCTV西班牙语,http://你的域名/文件名?act=play&vid=migu&id=609006450
            CCTV俄语,http://你的域名/文件名?act=play&vid=migu&id=609006446
            北京卫视,http://你的域名/文件名?act=play&vid=migu&id=630287636
            安徽卫视,http://你的域名/文件名?act=play&vid=migu&id=644933992
            江苏卫视,http://你的域名/文件名?act=play&vid=migu&id=623899540
            东方卫视,http://你的域名/文件名?act=play&vid=migu&id=651625930
            北京卫视,http://你的域名/文件名?act=play&vid=migu&id=630287661
            安徽卫视,http://你的域名/文件名?act=play&vid=migu&id=630971260
            广东卫视,http://你的域名/文件名?act=play&vid=migu&id=608831538
            南方卫视,http://你的域名/文件名?act=play&vid=migu&id=608917627
            山东教育,http://你的域名/文件名?act=play&vid=migu&id=609154353
            广西卫视,http://你的域名/文件名?act=play&vid=migu&id=634055160
            河南卫视,http://你的域名/文件名?act=play&vid=migu&id=635489820
            东南卫视,http://你的域名/文件名?act=play&vid=migu&id=651642156
            天津卫视,http://你的域名/文件名?act=play&vid=migu&id=631094458
            甘肃卫视,http://你的域名/文件名?act=play&vid=migu&id=630287549
            西藏卫视,http://你的域名/文件名?act=play&vid=migu&id=630291593
            兵团卫视,http://你的域名/文件名?act=play&vid=migu&id=630288004
            旅游卫视,http://你的域名/文件名?act=play&vid=migu&id=633215355
            重庆卫视,http://你的域名/文件名?act=play&vid=migu&id=630288006
            江西卫视,http://你的域名/文件名?act=play&vid=migu&id=630290852
            河北卫视,http://你的域名/文件名?act=play&vid=migu&id=630292528
            吉林卫视,http://你的域名/文件名?act=play&vid=migu&id=630288397
            辽宁卫视,http://你的域名/文件名?act=play&vid=migu&id=623583504
            山西卫视,http://你的域名/文件名?act=play&vid=migu&id=630289043
            厦门卫视,http://你的域名/文件名?act=play&vid=migu&id=630285654
            云南卫视,http://你的域名/文件名?act=play&vid=migu&id=630291417
            宁夏卫视,http://你的域名/文件名?act=play&vid=migu&id=630287436
            新疆卫视,http://你的域名/文件名?act=play&vid=migu&id=635385783
            青海卫视,http://你的域名/文件名?act=play&vid=migu&id=630287272
            陕西卫视,http://你的域名/文件名?act=play&vid=migu&id=630287233
            湖北卫视,http://你的域名/文件名?act=play&vid=migu&id=630288760
            贵州卫视,http://你的域名/文件名?act=play&vid=migu&id=631094827
            内蒙古卫视,http://你的域名/文件名?act=play&vid=migu&id=630287015
            黑龙江卫视,http://你的域名/文件名?act=play&vid=migu&id=630288601
            上海都市,http://你的域名/文件名?act=play&vid=migu&id=651638801
            上海都市,http://你的域名/文件名?act=play&vid=migu&id=651642246
            上海新闻综合,http://你的域名/文件名?act=play&vid=migu&id=651632657
            上海电视剧,http://你的域名/文件名?act=play&vid=migu&id=617290047
            上海新闻综合,http://你的域名/文件名?act=play&vid=migu&id=651638663
            上海纪实,http://你的域名/文件名?act=play&vid=migu&id=618954695
            上海外语,http://你的域名/文件名?act=play&vid=migu&id=618954688
            哈哈炫动,http://你的域名/文件名?act=play&vid=migu&id=651638619
            上海艺术人文,http://你的域名/文件名?act=play&vid=migu&id=651632875
            阿拉轧闹猛,http://你的域名/文件名?act=play&vid=migu&id=627033504
            上海老辰光,http://你的域名/文件名?act=play&vid=migu&id=639528181
            浙江少儿,http://你的域名/文件名?act=play&vid=migu&id=611318244
            杭州影视,http://你的域名/文件名?act=play&vid=migu&id=611373913
            杭州综合,http://你的域名/文件名?act=play&vid=migu&id=611354772
            南京新闻综合,http://你的域名/文件名?act=play&vid=migu&id=629243982
            南京十八,http://你的域名/文件名?act=play&vid=migu&id=629243989
            苏州新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731952
            无锡新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639737327
            常州新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731892
            扬州新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731888
            泰州新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731818
            盐城新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731825
            淮安新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731826
            镇江新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731783
            徐州新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731747
            宿迁新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731832
            连云港新闻综合,http://你的域名/文件名?act=play&vid=migu&id=639731715
            江苏综艺,http://你的域名/文件名?act=play&vid=migu&id=626065193
            江苏城市,http://你的域名/文件名?act=play&vid=migu&id=626064714
            公共新闻,http://你的域名/文件名?act=play&vid=migu&id=626064693
            江苏影视,http://你的域名/文件名?act=play&vid=migu&id=626064697
            体育休闲,http://你的域名/文件名?act=play&vid=migu&id=626064707
            江苏学习,http://你的域名/文件名?act=play&vid=migu&id=626881786
            江苏靓妆,http://你的域名/文件名?act=play&vid=migu&id=626064675
            优漫卡通,http://你的域名/文件名?act=play&vid=migu&id=626064703
            汉中综合,http://你的域名/文件名?act=play&vid=migu&id=650216404
            汉中公共,http://你的域名/文件名?act=play&vid=migu&id=650217163
            孝感公共,http://你的域名/文件名?act=play&vid=migu&id=638557579
            恩施新闻综合,http://你的域名/文件名?act=play&vid=migu&id=638811570
            恩施公共,http://你的域名/文件名?act=play&vid=migu&id=638811568
            长阳综合,http://你的域名/文件名?act=play&vid=migu&id=640773533
            赤壁二套,http://你的域名/文件名?act=play&vid=migu&id=638811534
            赤壁新闻综合,http://你的域名/文件名?act=play&vid=migu&id=638811454
            山西少儿,http://你的域名/文件名?act=play&vid=migu&id=628472619
            山西公共,http://你的域名/文件名?act=play&vid=migu&id=628472786
            山西科教,http://你的域名/文件名?act=play&vid=migu&id=628472792
            山西影视,http://你的域名/文件名?act=play&vid=migu&id=628472887
            北海新闻综合,http://你的域名/文件名?act=play&vid=migu&id=652487503
            北海经济科教,http://你的域名/文件名?act=play&vid=migu&id=653712739
            甘肃品质生活,http://你的域名/文件名?act=play&vid=migu&id=630641529
            甘肃移动电视,http://你的域名/文件名?act=play&vid=migu&id=630641593
            甘肃公共,http://你的域名/文件名?act=play&vid=migu&id=630641625
            甘肃都市,http://你的域名/文件名?act=play&vid=migu&id=630641756
            天津宁河综合新闻,http://你的域名/文件名?act=play&vid=migu&id=639176324
            贵阳电视台法制,http://你的域名/文件名?act=play&vid=migu&id=639176544
            贵阳电视台旅游生活,http://你的域名/文件名?act=play&vid=migu&id=639177347
            广东体育,http://你的域名/文件名?act=play&vid=migu&id=624303497
            南京教科,http://你的域名/文件名?act=play&vid=migu&id=629243936
            山西彩民在线,http://你的域名/文件名?act=play&vid=migu&id=628472211
            山西经济资讯,http://你的域名/文件名?act=play&vid=migu&id=628472942
            山西黄河电视台,http://你的域名/文件名?act=play&vid=migu&id=628473059
            漳县综合,http://你的域名/文件名?act=play&vid=migu&id=637620045
            北海公共,http://你的域名/文件名?act=play&vid=migu&id=653712657
            甘肃文化影视,http://你的域名/文件名?act=play&vid=migu&id=630641855
            CETV1,http://你的域名/文件名?act=play&vid=migu&id=649531772
            CETV1,http://你的域名/文件名?act=play&vid=migu&id=649531734
            CETV2,http://你的域名/文件名?act=play&vid=migu&id=649532169
            CETV3,http://你的域名/文件名?act=play&vid=migu&id=649531756
            CETV4,http://你的域名/文件名?act=play&vid=migu&id=649531725
            欢笑剧场,http://你的域名/文件名?act=play&vid=migu&id=623674859
            黄金剧场,http://你的域名/文件名?act=play&vid=migu&id=625155140
            军旅剧场,http://你的域名/文件名?act=play&vid=migu&id=625643517
            精品国产剧,http://你的域名/文件名?act=play&vid=migu&id=625574378
            乡村爱情剧场,http://你的域名/文件名?act=play&vid=migu&id=625774662
            激情夜场影院,http://你的域名/文件名?act=play&vid=migu&id=625188208
            红色谍战剧场,http://你的域名/文件名?act=play&vid=migu&id=634274665
            每日科幻电影,http://你的域名/文件名?act=play&vid=migu&id=625204865
            周星驰影院,http://你的域名/文件名?act=play&vid=migu&id=623338112
            追剧少女,http://你的域名/文件名?act=play&vid=migu&id=617432318
            怀旧老片,http://你的域名/文件名?act=play&vid=migu&id=621640582
            武侠剧场,http://你的域名/文件名?act=play&vid=migu&id=627198822
            动漫剧场,http://你的域名/文件名?act=play&vid=migu&id=627198751
            假期剧场,http://你的域名/文件名?act=play&vid=migu&id=627198692
            经典,http://你的域名/文件名?act=play&vid=migu&id=625542369
            精品剧场,http://你的域名/文件名?act=play&vid=migu&id=615810094
            四大名著剧场,http://你的域名/文件名?act=play&vid=migu&id=625498432
            东方电影,http://你的域名/文件名?act=play&vid=migu&id=623674834
            经典放映厅,http://你的域名/文件名?act=play&vid=migu&id=626157533
            射雕剧场,http://你的域名/文件名?act=play&vid=migu&id=625681367
            立面包青天,http://你的域名/文件名?act=play&vid=migu&id=625521420
            金庸,http://你的域名/文件名?act=play&vid=migu&id=625774640
            小戏骨剧场,http://你的域名/文件名?act=play&vid=migu&id=625526423
            华视火爆劲片,http://你的域名/文件名?act=play&vid=migu&id=624999147
            笑傲江湖,http://你的域名/文件名?act=play&vid=migu&id=625759558
            鹿鼎记,http://你的域名/文件名?act=play&vid=migu&id=625681368
            刘涛作品集,http://你的域名/文件名?act=play&vid=migu&id=625514969
            天龙八部集,http://你的域名/文件名?act=play&vid=migu&id=625703337
            盗墓方法论,http://你的域名/文件名?act=play&vid=migu&id=625525181
            咪咕早教,http://你的域名/文件名?act=play&vid=migu&id=617432495
            海底小纵队,http://你的域名/文件名?act=play&vid=migu&id=639528330
            男宝宝最爱,http://你的域名/文件名?act=play&vid=migu&id=639528180
            女宝宝最爱,http://你的域名/文件名?act=play&vid=migu&id=639528313
            少儿动漫,http://你的域名/文件名?act=play&vid=migu&id=615809462
            嘉佳卡通,http://你的域名/文件名?act=play&vid=migu&id=614952364
            游戏风云,http://你的域名/文件名?act=play&vid=migu&id=623674815
            法治天地,http://你的域名/文件名?act=play&vid=migu&id=631095330
            点掌财经,http://你的域名/文件名?act=play&vid=migu&id=638028966
            四海钓鱼,http://你的域名/文件名?act=play&vid=migu&id=650999610
            车迷,http://你的域名/文件名?act=play&vid=migu&id=622841891
            e娱乐,http://你的域名/文件名?act=play&vid=migu&id=608796678
            风尚音乐,http://你的域名/文件名?act=play&vid=migu&id=615809771
            江苏国际,http://你的域名/文件名?act=play&vid=migu&id=626064674
            江苏教育,http://你的域名/文件名?act=play&vid=migu&id=628008321
            温州新闻综合,http://你的域名/文件名?act=play&vid=migu&id=619253319
            温州经济科教,http://你的域名/文件名?act=play&vid=migu&id=619253317
            温州公共,http://你的域名/文件名?act=play&vid=migu&id=619253318
            温州都市生活,http://你的域名/文件名?act=play&vid=migu&id=619253313
            BBC独家,http://你的域名/文件名?act=play&vid=migu&id=633138330
            上视纪实,http://你的域名/文件名?act=play&vid=migu&id=617289997
            Discovery独家,http://你的域名/文件名?act=play&vid=migu&id=639528386
            Discovery王牌,http://你的域名/文件名?act=play&vid=migu&id=637483721
            BBC地平线,http://你的域名/文件名?act=play&vid=migu&id=637444830
            新片放映厅,http://你的域名/文件名?act=play&vid=migu&id=619495952
            高分影院,http://你的域名/文件名?act=play&vid=migu&id=627198191
            上海电视剧,http://你的域名/文件名?act=play&vid=migu&id=618954718
            上海星尚,http://你的域名/文件名?act=play&vid=migu&id=618954743
            上海星尚,http://你的域名/文件名?act=play&vid=migu&id=617289989
            上海第一财经,http://你的域名/文件名?act=play&vid=migu&id=608780988
            浙江影视,http://你的域名/文件名?act=play&vid=migu&id=611352814
            浙江经视,http://你的域名/文件名?act=play&vid=migu&id=618086453
            天津滨海综艺,http://你的域名/文件名?act=play&vid=migu&id=608933884
            福建厦门二套,http://你的域名/文件名?act=play&vid=migu&id=608938934
            福建厦门一套,http://你的域名/文件名?act=play&vid=migu&id=608937190
            新疆哈语综合,http://你的域名/文件名?act=play&vid=migu&id=608937201
            新疆维语综合,http://你的域名/文件名?act=play&vid=migu&id=609186896
            新疆哈语综艺,http://你的域名/文件名?act=play&vid=migu&id=609186850
            新疆维语综艺,http://你的域名/文件名?act=play&vid=migu&id=609186895
            南方影视,http://你的域名/文件名?act=play&vid=migu&id=614961829
            新乡新闻综合,http://你的域名/文件名?act=play&vid=migu&id=616380043
            嘉峪关公共,http://你的域名/文件名?act=play&vid=migu&id=614954833
            嘉峪关综合,http://你的域名/文件名?act=play&vid=migu&id=614954130
            宁河新闻,http://你的域名/文件名?act=play&vid=migu&id=625586032
            央广购物,http://你的域名/文件名?act=play&vid=migu&id=617089949
            风尚购物,http://你的域名/文件名?act=play&vid=migu&id=615797398
            中国黄河电视台,http://你的域名/文件名?act=play&vid=migu&id=628472544
        ');
    }
    
    if ($vid == 'nnzb') {
        $channellist = array('
            # 央视 #
            CCTV-1,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=169
            CCTV-2,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=168
            CCTV-3,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=167
            CCTV-4,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=166
            CCTV-5,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=165
            CCTV-6,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=164
            CCTV-7,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=163
            CCTV-8,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=162
            CCTV-9,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=161
            CCTV-10,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=160
            CCTV-11,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=159
            CCTV-12,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=158
            CCTV-13,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=157
            CCTV-14,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=156
            CCTV-15,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=155
            CCTV-5Plus,http://你的域名/文件名?act=play&vid=nnzb&tid=1&id=154
            # 卫视 #
            深圳卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=620
            北京卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=200
            东方卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=199
            天津卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=198
            重庆卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=197
            安徽卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=196
            浙江卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=195
            江苏卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=194
            湖南卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=193
            湖北卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=192
            河南卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=191
            河北卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=190
            广东卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=189
            广西卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=188
            山东卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=187
            山西卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=186
            四川卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=185
            江西卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=184
            东南卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=183
            吉林卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=182
            辽宁卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=181
            云南卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=180
            海南卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=179
            陕西卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=178
            甘肃卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=177
            宁夏卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=176
            青海卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=175
            贵州卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=174
            新疆卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=173
            西藏卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=172
            内蒙古卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=171
            黑龙江卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=2&id=170
            # 地方 #
            湖南都市频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=720
            安徽经济生活,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=682
            安徽影视,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=681
            西安新闻综合频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=529
            西安白鹤都市频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=528
            西安文化影视频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=527
            西安音乐综艺频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=526
            西安商务资讯频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=525
            西安健康快乐频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=524
            河北卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=429&line=2
            河北经济频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=428
            河北都市频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=427
            河北影视频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=426
            河北少儿科教频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=425
            河北公共频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=424
            河北农民频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=423
            石家庄新闻综合频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=422
            石家庄娱乐频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=421
            石家庄生活频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=420
            石家庄都市频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=419
            河南卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=356
            湖南经视频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=355
            湖南娱乐频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=354
            湖南电视剧频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=353
            湖南公共频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=352
            湖南国际频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=351
            金鹰纪实频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=350
            金鹰卡通卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=349
            长沙新闻综合频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=348
            东方电影频道,http://你的域名/文件名?act=play&vid=nnzb&tid=4&id=228
            # 港台 #
            凤凰中文,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=100
            凤凰资讯,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=99
            凤凰香港,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=98
            凤凰电影,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=97
            凤凰美洲,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=96
            Channel V,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=95
            香港卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=93
            星空卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=92
            阳光卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=90
            澳亚卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=89
            莲花卫视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=88
            寰宇新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=85
            寰宇新闻2台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=84
            无线财经台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=79
            TVB翡翠台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=78
            TVB明珠台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=77&line=2
            TVB星河台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=76
            TVBJ2,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=74
            无线新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=73
            TVB功夫台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=72
            有线新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=62
            有线电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=61
            有线18台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=59
            有线好莱坞电影,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=54
            澳视体育台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=50
            澳视卫星台MACAU,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=48
            台湾中视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=47
            台湾华视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=46
            台湾台视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=45
            台湾民视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=44
            台湾公视,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=43
            中天新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=42
            中天综合台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=41
            中天娱乐台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=40
            中天亚洲台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=39
            TVBS新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=38
            TVBS综合台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=37
            TVBS欢乐台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=36
            壹电视综合台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=35
            壹电视新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=34
            东森综合台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=32
            东森幼幼台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=31
            东森电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=29
            东森洋片台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=28
            三立新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=26
            三立都会台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=25
            三立台湾台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=24
            八大综合台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=22
            八大第一台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=21
            八大娱乐K台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=20
            卫视电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=16
            天映电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=15
            龙祥电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=14
            龙祥时代电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=13
            纬来综合台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=12
            纬来体育台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=11
            纬来日本台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=10
            纬来电影台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=9
            非凡新闻台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=6
            卫视中文台,http://你的域名/文件名?act=play&vid=nnzb&tid=3&id=4
            # 国外 #
            俄罗斯红星台,http://你的域名/文件名?act=play&vid=nnzb&tid=5&id=118
        ');
    }
    
    if ($vid == 'null') {
        $channellist = array('
            # 港台 #
            CCTV-1,http://你的域名/文件名?act=play&vid=smart&id=cctv1
            CCTV-2,http://你的域名/文件名?act=play&vid=smart&id=cctv2
            CCTV-4,http://你的域名/文件名?act=play&vid=smart&id=cctv4_twn
            CCTV-4,http://你的域名/文件名?act=play&vid=smart&id=Cctv4
            CCTV-5,http://你的域名/文件名?act=play&vid=smart&id=cctv5
            CCTV-5Plus,http://你的域名/文件名?act=play&vid=smart&id=cctv5plus
            CCTV-6,http://你的域名/文件名?act=play&vid=smart&id=cctv6
            CCTV-7,http://你的域名/文件名?act=play&vid=smart&id=cctv7
            CCTV-8,http://你的域名/文件名?act=play&vid=smart&id=cctv8hd
            CCTV-9,http://你的域名/文件名?act=play&vid=smart&id=cctv9hd
            CCTV-10,http://你的域名/文件名?act=play&vid=smart&id=cctv10hd
            CCTV-11,http://你的域名/文件名?act=play&vid=smart&id=cctv11
            CCTV-12,http://你的域名/文件名?act=play&vid=smart&id=cctv12
            CCTV-13,http://你的域名/文件名?act=play&vid=smart&id=Ctv13
            CCTV-14,http://你的域名/文件名?act=play&vid=smart&id=cctv14
            CCTV-15,http://你的域名/文件名?act=play&vid=smart&id=cctv15
            CGTN-1,http://你的域名/文件名?act=play&vid=smart&id=CGTN
            CHC动作电影,http://你的域名/文件名?act=play&vid=smart&id=chcaction
            CHC家庭影院,http://你的域名/文件名?act=play&vid=smart&id=chcfamily
            CHC高清电影,http://你的域名/文件名?act=play&vid=smart&id=chchdmovie
            中国电影,http://你的域名/文件名?act=play&vid=smart&id=chinamovie_twn
            都市剧场,http://你的域名/文件名?act=play&vid=smart&id=moviehd_twn
            新视觉HD,http://你的域名/文件名?act=play&vid=smart&id=xinshijue
            怀旧剧场,http://你的域名/文件名?act=play&vid=smart&id=cctvclassic
            高尔夫.网球,http://你的域名/文件名?act=play&vid=smart&id=gaoerfuwangqiu
            足球风云,http://你的域名/文件名?act=play&vid=smart&id=fengyunzuqiu
            中华美食,http://你的域名/文件名?act=play&vid=smart&id=foodnetwork_twn
            北京卫视,http://你的域名/文件名?act=play&vid=smart&id=beijing
            东方卫视,http://你的域名/文件名?act=play&vid=smart&id=dongfangweishi
            湖南卫视,http://你的域名/文件名?act=play&vid=smart&id=Hunan
            湖南卫视,http://你的域名/文件名?act=play&vid=smart&id=hunan_twn
            江苏卫视,http://你的域名/文件名?act=play&vid=smart&id=Jiangsu
            江苏卫视,http://你的域名/文件名?act=play&vid=smart&id=jiangsu_twn
            浙江卫视,http://你的域名/文件名?act=play&vid=smart&id=Zhejiang
            浙江卫视,http://你的域名/文件名?act=play&vid=smart&id=zhejiang_twn
            重庆影视,http://你的域名/文件名?act=play&vid=smart&id=axn_twn
            重庆卫视,http://你的域名/文件名?act=play&vid=smart&id=chongqingweishi
            东南卫视,http://你的域名/文件名?act=play&vid=smart&id=fujian
            南方卫视,http://你的域名/文件名?act=play&vid=smart&id=gdnanfang2
            广东体育,http://你的域名/文件名?act=play&vid=smart&id=gdsports
            广东体育,http://你的域名/文件名?act=play&vid=smart&id=guangdongsport
            广东卫视,http://你的域名/文件名?act=play&vid=smart&id=guangdongmovie
            广西卫视,http://你的域名/文件名?act=play&vid=smart&id=guangxi
            天津卫视,http://你的域名/文件名?act=play&vid=smart&id=tianjinweishi
            深圳卫视,http://你的域名/文件名?act=play&vid=smart&id=shenzhen
            广东珠江,http://你的域名/文件名?act=play&vid=smart&id=zhujiang
            珠江电影,http://你的域名/文件名?act=play&vid=smart&id=zhujiangmovie
            湖北卫视,http://你的域名/文件名?act=play&vid=smart&id=hubei
            江西卫视,http://你的域名/文件名?act=play&vid=smart&id=jiangxiweishi
            凤凰资讯,http://你的域名/文件名?act=play&vid=smart&id=phoenixinfo_hd
            凤凰中文,http://你的域名/文件名?act=play&vid=smart&id=phoenixtv_hd
            凤凰香港,http://你的域名/文件名?act=play&vid=smart&id=hkphoenix_twn
            翡翠台,http://你的域名/文件名?act=play&vid=smart&id=jade_twn
            明珠台,http://你的域名/文件名?act=play&vid=smart&id=pearl_twn
            无线新闻,http://你的域名/文件名?act=play&vid=smart&id=inews_twn
            无线资讯,http://你的域名/文件名?act=play&vid=smart&id=j5_twn
            有线新闻,http://你的域名/文件名?act=play&vid=smart&id=hkcnews_twn
            星河频道,http://你的域名/文件名?act=play&vid=smart&id=tvbxinghe_twn
            J2,http://你的域名/文件名?act=play&vid=smart&id=j2_twn
            ViuTV,http://你的域名/文件名?act=play&vid=smart&id=viu_twn
            ViuTV,http://你的域名/文件名?act=play&vid=smart&id=viu1_twn
            ViuTV6,http://你的域名/文件名?act=play&vid=smart&id=viu6_twn
            港台电视31,http://你的域名/文件名?act=play&vid=smart&id=rhk31_twn
            港台电视32,http://你的域名/文件名?act=play&vid=smart&id=rhk32_twn
            卫视电影,http://你的域名/文件名?act=play&vid=smart&id=xingwei_movie
            卫视电影,http://你的域名/文件名?act=play&vid=smart&id=warnatv_twn
            星空卫视,http://你的域名/文件名?act=play&vid=smart&id=xingkong
            澳门莲花,http://你的域名/文件名?act=play&vid=smart&id=macaulotus
            中视经典,http://你的域名/文件名?act=play&vid=smart&id=zhongshi_twn
            中视新闻,http://你的域名/文件名?act=play&vid=smart&id=zhongshinews_twn
            民视,http://你的域名/文件名?act=play&vid=smart&id=ftvhd_taiwan
            民视新闻,http://你的域名/文件名?act=play&vid=smart&id=ftvnew_taiwan
            民视台湾,http://你的域名/文件名?act=play&vid=smart&id=ftvtaiwan_twn
            台视,http://你的域名/文件名?act=play&vid=smart&id=ttv_taiwan
            台视新闻,http://你的域名/文件名?act=play&vid=smart&id=ttvnews_twn
            华视,http://你的域名/文件名?act=play&vid=smart&id=ctshd_twn
            华视HD,http://你的域名/文件名?act=play&vid=smart&id=zhongshihd_twn
            公视,http://你的域名/文件名?act=play&vid=smart&id=ctv_taiwan
            大爱,http://你的域名/文件名?act=play&vid=smart&id=daai_twn
            采昌,http://你的域名/文件名?act=play&vid=smart&id=bosiunlimited_twn
            采昌,http://你的域名/文件名?act=play&vid=smart&id=caichangmovie
            年代新闻HD,http://你的域名/文件名?act=play&vid=smart&id=niandainews_twn
            TVBSHD,http://你的域名/文件名?act=play&vid=smart&id=tvbs
            TVBS欢乐HD,http://你的域名/文件名?act=play&vid=smart&id=tvbs_g
            TVBS欢乐HD,http://你的域名/文件名?act=play&vid=smart&id=tvbshuanle_twn
            TVBS新闻HD,http://你的域名/文件名?act=play&vid=smart&id=tvbs_n
            八大戏剧,http://你的域名/文件名?act=play&vid=smart&id=badadrama
            八大娱乐,http://你的域名/文件名?act=play&vid=smart&id=badaentertain
            八大一台,http://你的域名/文件名?act=play&vid=smart&id=badafirst
            八大综合,http://你的域名/文件名?act=play&vid=smart&id=badazhonghe
            中天亚洲,http://你的域名/文件名?act=play&vid=smart&id=ctiasia_twn
            中天亚洲,http://你的域名/文件名?act=play&vid=smart&id=ettvasia_twn
            中天娱乐,http://你的域名/文件名?act=play&vid=smart&id=ctient
            中天新闻,http://你的域名/文件名?act=play&vid=smart&id=ctinews
            中天综合,http://你的域名/文件名?act=play&vid=smart&id=ctizhonghe
            东森综合HD,http://你的域名/文件名?act=play&vid=smart&id=ettvzhonghe
            东森财经,http://你的域名/文件名?act=play&vid=smart&id=ettvcaijing_twn
            东森戏剧,http://你的域名/文件名?act=play&vid=smart&id=ettvdrama
            东森电影,http://你的域名/文件名?act=play&vid=smart&id=ettvmovie
            东森新闻,http://你的域名/文件名?act=play&vid=smart&id=ettvnews
            东森新闻HD,http://你的域名/文件名?act=play&vid=smart&id=ettvnews1
            东森戏剧HD,http://你的域名/文件名?act=play&vid=smart&id=ettvwestern
            东森呦呦,http://你的域名/文件名?act=play&vid=smart&id=yoyo_twn
            ELTA综合,http://你的域名/文件名?act=play&vid=smart&id=eltazhonghe_twn
            ELTA影剧,http://你的域名/文件名?act=play&vid=smart&id=eltadrama_twn
            ELTA体育1,http://你的域名/文件名?act=play&vid=smart&id=eltasport_twn
            ELTA体育3,http://你的域名/文件名?act=play&vid=smart&id=eltasports3_twn
            ELTA体育2,http://你的域名/文件名?act=play&vid=smart&id=eltayule_twn
            晴天卡通,http://你的域名/文件名?act=play&vid=smart&id=jingtiancartoon_twn
            晴天国际,http://你的域名/文件名?act=play&vid=smart&id=jingtianintl
            晴天日本,http://你的域名/文件名?act=play&vid=smart&id=jingtianjapan
            晴天电影,http://你的域名/文件名?act=play&vid=smart&id=jingtianmovie_twn
            晴天影剧,http://你的域名/文件名?act=play&vid=smart&id=jingtianxiju
            晴天映画,http://你的域名/文件名?act=play&vid=smart&id=jingtianyinghua_twn
            晴天育乐,http://你的域名/文件名?act=play&vid=smart&id=jingtianyule
            晴天戏剧,http://你的域名/文件名?act=play&vid=smart&id=jingyangxiju_twn
            龙华动画,http://你的域名/文件名?act=play&vid=smart&id=lunghuaanimation_twn
            龙华经典,http://你的域名/文件名?act=play&vid=smart&id=lunghuaclassic
            龙华偶像,http://你的域名/文件名?act=play&vid=smart&id=lunghuaidol_twn
            龙华影剧,http://你的域名/文件名?act=play&vid=smart&id=lunghuamovie_twn
            龙华洋片,http://你的域名/文件名?act=play&vid=smart&id=lunghuawestern_twn
            龙华戏剧,http://你的域名/文件名?act=play&vid=smart&id=lunghuaxiju_twn
            龙祥电影,http://你的域名/文件名?act=play&vid=smart&id=lungxiangtime_twn
            三立都会HD,http://你的域名/文件名?act=play&vid=smart&id=sanlidouhui
            三立新闻HD,http://你的域名/文件名?act=play&vid=smart&id=sanlinews
            三立台湾HD,http://你的域名/文件名?act=play&vid=smart&id=sanlitaiwan
            三立戏剧,http://你的域名/文件名?act=play&vid=smart&id=sanlixiju
            三立综合,http://你的域名/文件名?act=play&vid=smart&id=sanlizhonghe
            壹综合,http://你的域名/文件名?act=play&vid=smart&id=onetvzonghe
            壹新闻,http://你的域名/文件名?act=play&vid=smart&id=Nexttvnews
            壹新闻HD,http://你的域名/文件名?act=play&vid=smart&id=onetvnews
            环宇综合,http://你的域名/文件名?act=play&vid=smart&id=kuanyuhdzhonghe_twn
            环宇财经,http://你的域名/文件名?act=play&vid=smart&id=kuanyubiz_twn
            环宇新闻,http://你的域名/文件名?act=play&vid=smart&id=kuanyunews1
            环宇新闻2,http://你的域名/文件名?act=play&vid=smart&id=videolandjapan_twn
            纬来电影HD,http://你的域名/文件名?act=play&vid=smart&id=videolandmovie
            纬来精彩HD,http://你的域名/文件名?act=play&vid=smart&id=videolandspecial_twn
            纬来体育HD,http://你的域名/文件名?act=play&vid=smart&id=videolandsport_twn
            纬来戏剧HD,http://你的域名/文件名?act=play&vid=smart&id=videolandxiju_twn
            纬来育乐HD,http://你的域名/文件名?act=play&vid=smart&id=videolandyule
            纬来综合HD,http://你的域名/文件名?act=play&vid=smart&id=videolandzhe_twn
            华艺影剧,http://你的域名/文件名?act=play&vid=smart&id=hongjimovie_twn
            美食星球,http://你的域名/文件名?act=play&vid=smart&id=chinesefoodnetwork
            动物星球,http://你的域名/文件名?act=play&vid=smart&id=animalplanet_twn
            亚洲旅游,http://你的域名/文件名?act=play&vid=smart&id=asiatravel_twn
            国兴卫视,http://你的域名/文件名?act=play&vid=smart&id=guoxingweishi_twn
            迪蔓日本,http://你的域名/文件名?act=play&vid=smart&id=mandijapan_twn
            星卫娱乐,http://你的域名/文件名?act=play&vid=smart&id=starentertainment_twn
            美亚电影,http://你的域名/文件名?act=play&vid=smart&id=meiyamovie_twn
            好莱坞电影,http://你的域名/文件名?act=play&vid=smart&id=hollywoodmovies_twn
            华纳电影,http://你的域名/文件名?act=play&vid=smart&id=weishimovie_twn
            博斯高球1,http://你的域名/文件名?act=play&vid=smart&id=boomerang_twn
            博斯高球2,http://你的域名/文件名?act=play&vid=smart&id=bosigolf1_twn
            博斯高球2,http://你的域名/文件名?act=play&vid=smart&id=golf_twn
            博斯运动2,http://你的域名/文件名?act=play&vid=smart&id=bosigolf2_twn
            博斯运动1,http://你的域名/文件名?act=play&vid=smart&id=bosisport2_twn
            博斯运动1,http://你的域名/文件名?act=play&vid=smart&id=skynews_twn
            博斯网球,http://你的域名/文件名?act=play&vid=smart&id=bosisport_twn
            博斯无限,http://你的域名/文件名?act=play&vid=smart&id=bositennis_twn
            马来西亚体育1,http://你的域名/文件名?act=play&vid=smart&id=s_1365a3ea_1880
            马来西亚体育1,http://你的域名/文件名?act=play&vid=smart&id=supersports1
            马来西亚体育2,http://你的域名/文件名?act=play&vid=smart&id=s_a1133d50_1928
            马来西亚体育2,http://你的域名/文件名?act=play&vid=smart&id=supersports2
            马来西亚体育3,http://你的域名/文件名?act=play&vid=smart&id=s_f0a98bfa_1881
            马来西亚体育3,http://你的域名/文件名?act=play&vid=smart&id=supersports3
            马来西亚体育4,http://你的域名/文件名?act=play&vid=smart&id=s_6c4db083_1918
            马来西亚体育4,http://你的域名/文件名?act=play&vid=smart&id=supersports4
            天映频道,http://你的域名/文件名?act=play&vid=smart&id=Celestial1511
            天映经典,http://你的域名/文件名?act=play&vid=smart&id=Celestial2
            最爱电影,http://你的域名/文件名?act=play&vid=smart&id=sundance_twn
            皇家足球,http://你的域名/文件名?act=play&vid=smart&id=truepre1_pat
            皇家足球2,http://你的域名/文件名?act=play&vid=smart&id=truepre2_pat
            新加坡5,http://你的域名/文件名?act=play&vid=smart&id=Channel5
            新加坡8,http://你的域名/文件名?act=play&vid=smart&id=Channel8
            CN卡通,http://你的域名/文件名?act=play&vid=smart&id=momo1_twn
            E体育1,http://你的域名/文件名?act=play&vid=smart&id=golfchannel_twn
            E体育2,http://你的域名/文件名?act=play&vid=smart&id=luxetv_twn
            EVE旅游,http://你的域名/文件名?act=play&vid=smart&id=eyetvtravel_twn
            EVE戏剧,http://你的域名/文件名?act=play&vid=smart&id=eyetvxiju_twn
            History1,http://你的域名/文件名?act=play&vid=smart&id=history1hd_twn
            History2,http://你的域名/文件名?act=play&vid=smart&id=history2hd_twn
            ci,http://你的域名/文件名?act=play&vid=smart&id=ci_twn
            cinemaworld,http://你的域名/文件名?act=play&vid=smart&id=cinemaworld_twn
            cinemax,http://你的域名/文件名?act=play&vid=smart&id=cinemax_twn
            cnbc,http://你的域名/文件名?act=play&vid=smart&id=cnbc_twn
            cnn,http://你的域名/文件名?act=play&vid=smart&id=cnn_twn
            DW,http://你的域名/文件名?act=play&vid=smart&id=dw_twn
            BBC earth,http://你的域名/文件名?act=play&vid=smart&id=bbcearth
            BBC earth,http://你的域名/文件名?act=play&vid=smart&id=bbcearthhd
            BBC lifestyle,http://你的域名/文件名?act=play&vid=smart&id=bbcearthlifestyle
            BBC news,http://你的域名/文件名?act=play&vid=smart&id=bbcnews_twn
            HBOHD,http://你的域名/文件名?act=play&vid=smart&id=hbohd_twn
            HBOhits,http://你的域名/文件名?act=play&vid=smart&id=hbohits_twn
            HBOsignature,http://你的域名/文件名?act=play&vid=smart&id=hbosignature_twn
            FOXHD,http://你的域名/文件名?act=play&vid=smart&id=foxfamily_twn
            FOXaction,http://你的域名/文件名?act=play&vid=smart&id=foxaction_twn
            discoverych,http://你的域名/文件名?act=play&vid=smart&id=discoverych_twn
            eve,http://你的域名/文件名?act=play&vid=smart&id=discoveryeve_twn
            discovery,http://你的域名/文件名?act=play&vid=smart&id=discoveryhd_twn
            discoverysc,http://你的域名/文件名?act=play&vid=smart&id=discoverysc_twn
            DMAX,http://你的域名/文件名?act=play&vid=smart&id=discoveryturbo_twn
            discoverytwn,http://你的域名/文件名?act=play&vid=smart&id=discoverytwn_twn
            junior,http://你的域名/文件名?act=play&vid=smart&id=disneyjunior_glo
            disneytwn,http://你的域名/文件名?act=play&vid=smart&id=disneytwn_twn
            disneyxd,http://你的域名/文件名?act=play&vid=smart&id=disneyxd_glo
            CBeedies,http://你的域名/文件名?act=play&vid=smart&id=diva_twn
            Ohk,http://你的域名/文件名?act=play&vid=smart&id=Ohk
            Ria,http://你的域名/文件名?act=play&vid=smart&id=Ria
            SetOne,http://你的域名/文件名?act=play&vid=smart&id=SetOne
            TVN,http://你的域名/文件名?act=play&vid=smart&id=TVN
            TVN,http://你的域名/文件名?act=play&vid=smart&id=tvn_twn
            Warna,http://你的域名/文件名?act=play&vid=smart&id=Warna
            Warna,http://你的域名/文件名?act=play&vid=smart&id=Warner_backup
            abcnews,http://你的域名/文件名?act=play&vid=smart&id=abcnews_glo
            aljazeera,http://你的域名/文件名?act=play&vid=smart&id=aljazeera_twn
            aod,http://你的域名/文件名?act=play&vid=smart&id=aod361_twn
            afn,http://你的域名/文件名?act=play&vid=smart&id=asiafood_twn
            ass4,http://你的域名/文件名?act=play&vid=smart&id=ass4_gloyk1511
            babyfirst,http://你的域名/文件名?act=play&vid=smart&id=babyfirst_twn
            babytv,http://你的域名/文件名?act=play&vid=smart&id=babytv_twn
            bloomberg,http://你的域名/文件名?act=play&vid=smart&id=bloomberg_twn
            ANIMAX,http://你的域名/文件名?act=play&vid=smart&id=cartoonnetwork_twn
            e,http://你的域名/文件名?act=play&vid=smart&id=e_twn
            fashiontv,http://你的域名/文件名?act=play&vid=smart&id=fashiontv_twn
            FOX3,http://你的域名/文件名?act=play&vid=smart&id=foxhd_twn
            foxsport,http://你的域名/文件名?act=play&vid=smart&id=foxsport_twn
            france24,http://你的域名/文件名?act=play&vid=smart&id=france24_twn
            FXHD,http://你的域名/文件名?act=play&vid=smart&id=fxhd_twn
            NOW,http://你的域名/文件名?act=play&vid=smart&id=fyi_twn
            lifetime,http://你的域名/文件名?act=play&vid=smart&id=lifetime_glo
            mezzo,http://你的域名/文件名?act=play&vid=smart&id=mezzolive_twn
            MSNBC,http://你的域名/文件名?act=play&vid=smart&id=msnbc_glo
            MTV,http://你的域名/文件名?act=play&vid=smart&id=mtvlive_twn
            MTVTW,http://你的域名/文件名?act=play&vid=smart&id=mtvtaiwan_twn
            MTVMG,http://你的域名/文件名?act=play&vid=smart&id=mtvusa_glo
            KIDS,http://你的域名/文件名?act=play&vid=smart&id=mykids_twn
            natgeohd,http://你的域名/文件名?act=play&vid=smart&id=natgeohd_twn
            natgeopeople,http://你的域名/文件名?act=play&vid=smart&id=natgeopeople_twn
            natgeowild,http://你的域名/文件名?act=play&vid=smart&id=natgeowild_twn
            NBN,http://你的域名/文件名?act=play&vid=smart&id=nbausa_glo
            nbc_glo,http://你的域名/文件名?act=play&vid=smart&id=nbc_glo
            nbcgolf,http://你的域名/文件名?act=play&vid=smart&id=nbcgolf_glo
            nbcsn,http://你的域名/文件名?act=play&vid=smart&id=nbcsn_glo
            nickjr,http://你的域名/文件名?act=play&vid=smart&id=nickelodeon_twn
            nickjr,http://你的域名/文件名?act=play&vid=smart&id=nickjr_twn
            OHK,http://你的域名/文件名?act=play&vid=smart&id=ohk_twn
            outdoorsports,http://你的域名/文件名?act=play&vid=smart&id=outdoorsports_twn
            russiantime,http://你的域名/文件名?act=play&vid=smart&id=russiantime_twn
            SMART,http://你的域名/文件名?act=play&vid=smart&id=smartknowledge
            OEN,http://你的域名/文件名?act=play&vid=smart&id=sonyhd_twn
            syfy,http://你的域名/文件名?act=play&vid=smart&id=syfy_glo
            253,http://你的域名/文件名?act=play&vid=smart&id=thethao_viet
            TLC,http://你的域名/文件名?act=play&vid=smart&id=tlcasia_twn
            TLC,http://你的域名/文件名?act=play&vid=smart&id=travelchannel_twn
            PGTV,http://你的域名/文件名?act=play&vid=smart&id=travelch_glo
            261,http://你的域名/文件名?act=play&vid=smart&id=truepre3_pat
            262,http://你的域名/文件名?act=play&vid=smart&id=truepre4_pat
            263,http://你的域名/文件名?act=play&vid=smart&id=truepre5_pat
            TNT,http://你的域名/文件名?act=play&vid=smart&id=trutv_glo
            267,http://你的域名/文件名?act=play&vid=smart&id=tvbcaijing_twn
            WWE,http://你的域名/文件名?act=play&vid=smart&id=weishiwestern_twn
            288,http://你的域名/文件名?act=play&vid=smart&id=wwe_twn
        ');
    }
?>